services:
  - type: web
    name: airbnb-scraper
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node src/index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: chrome-cache
      mountPath: /opt/render/project/.chrome
      sizeGB: 1
    healthCheckPath: /
    buildFilter:
      paths:
        - src/**
        - package.json
        - package-lock.json
        - build-chrome.js 