services:
  - type: web
    name: airbnb-scraper-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: chromium-cache
      mountPath: /tmp/puppeteer_cache
      sizeGB: 1
    healthCheckPath: / 