services:
  - type: web
    name: airbnb-scraper
    env: node
    plan: free
    buildCommand: ./render-build.sh
    startCommand: export PATH="${PATH}:/opt/render/project/.render/chrome/opt/google/chrome"; npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: CHROME_BIN
        value: /opt/render/project/.render/chrome/opt/google/chrome/chrome
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/project/.render/chrome/opt/google/chrome/chrome
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: chromium-cache
      mountPath: /opt/render/project/.cache
      sizeGB: 1
    healthCheckPath: /
    buildFilter:
      paths:
        - src/**
        - package.json
        - package-lock.json 