services:
  - type: web
    name: airbnb-scraper
    env: node
    plan: free
    buildCommand: npm install
    startCommand: PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: chrome-cache
      mountPath: /opt/render/project/.cache
      sizeGB: 1
    healthCheckPath: /
    buildFilter:
      paths:
        - src/**
        - package.json
        - package-lock.json
        - build-chrome.js 