services:
  - type: web
    name: airbnb-scraper-api
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "/tmp"
      - key: DEBUG
        value: "pw:api"
    scaling:
      minInstances: 1
      maxInstances: 1
    healthCheckPath: / 