services:
  - type: web
    name: airbnb-scraper-api
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
    scaling:
      minInstances: 1
      maxInstances: 1
    healthCheckPath: / 