services:
  - type: web
    name: airbnb-scraper
    env: node
    plan: free
    buildCommand: ./render-build.sh
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.cache/puppeteer
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: chromium-cache
      mountPath: /opt/render/project/.cache
      sizeGB: 1
    healthCheckPath: /
    buildFilter:
      paths:
        - src/**
        - package.json
        - package-lock.json 